src/urls.py
from django.contrib import admin
from django.urls import path,include
from .yasg import urlpatterns as doc_urls 

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('my_app.urls')),
    path('user/', include('accounts.urls')),
]
urlpatterns += doc_urls

my_app/models.py
from django.db import models
from accounts.models import User
# from django.contrib.auth.models import User

class Product(models.Model):
	product_name = models.CharField(max_length = 200)
	product_compound = models.TextField()
	product_price = models.FloatField()
	product_image = models.ImageField(upload_to = 'image/')

	def __str__(self):
		return self.product_name  


class Coment(models.Model):
	username = models.CharField(max_length = 150)         
	phone = models.CharField(max_length = 20)
	email = models.CharField(max_length = 50)
	message = models.TextField()
	date = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return f'{self.username}'


# 1- bosqich 

# order yaniy mahsulotmi savatga qushish uchun model
# from django.contrib.auth.models import User

class Order(models.Model):
	customer = models.ForeignKey(User, on_delete=models.SET_NULL, blank = True, null = True)
	data_ordered = models.DateTimeField(auto_now_add = True)
	name = models.CharField(max_length = 200, null = True)
	complete = models.BooleanField(default = False, null = True, blank = False)

	"""pastdagi quantity(mahsulotlarni sonini) va 
	barcha orderItem(savatdagi mahsulotlar)ni hisoblash uchun"""
	@property #Dekorator
	def get_card_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total	

	"""pastdagi get_total funksiyadan aytgan qiymatni barcha orderItem
	(savatdagi mahsulotlar) larni husoblaash uchun"""
	@property # Dekorator
	def get_card_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	#String obyektini qaytaradi
	def __str__(self):
		return str(self.id)


# Mahsulotni qachon ba kim tomonidan qaysi qushilhanligini saqlash uchun model
class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete = models.SET_NULL, blank = True, null = True)
	order = models.ForeignKey(Order, on_delete = models.SET_NULL, blank = True, null = True)
	quantity = models.IntegerField(default = 0, null = True, blank = True)
	data_added = models.DateTimeField(auto_now_add = True)

	#mahsulot narxni soniga kopaytirib beradi
	@property #Dekorator
	def get_total(self):
		total = self.product.product_price * self.quantity
		return total

	# String obyektini qaytaradi
	def __str__(self):
		return str(self.id)
	

templates/about.html
{% extends 'base.html' %}

{% block content %}
    <!-- end header section -->
  </div>

  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container  ">

      <div class="row">
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                We Are Asaman
              </h2>
            </div>
            <p>
              Asaman is a fully licensed specialty pharmaceutical distributor, assisting a wide range of clients with their clinical trial needs.

                We are not your average pharmaceutical distributor.

              Asaman specializes in pharmaceutical procurement of comparator drugs, often those necessary for the most complex clinical trials. We are dedicated to making the clinical trial process simpler, by distributing high quality comparator drugs in a timely, precise and cost efficient manner.
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

  <!-- footer section -->
{% endblock content %}

templates/base.html
{% load static %}

<script type="text/javascript">
    var user = '{{ request.user }}'
</script>

<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/asamanlogo.png' %}" type="">

  <title> Asaman </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />


  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

  <!-- Mahsulotlarni tartiblash -->
  <style>
    #soz{
      white-space:  nowrap;
      text-overflow:  ellipsis;
      overflow: hidden;
    }
  </style>

  <style>
/* Style The Dropdown Button */
.dropbtn {
        display: inline-block;
    padding: 10px 45px;
    background-color: #ffbe33;
    color: #ffffff;
    border-radius: 45px;
    -webkit-transition: all 0.3s;
    transition: all 0.3s;
    border: none;
    margin-top: 10px;
}
}

/* The container <div> - needed to position the dropdown content */
.dropdown {
  position: relative;
  display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {
  display: none;
  position: absolute;

  min-width: 150px;
 /* box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);*/
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  border-radius: 45px;

}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #yellow;
color: #ffbe33;}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {
  display: block;
}

.dropdown:hover .dropbtn {
  background-color: #3e8e41;
}
</style>

<!-- keyingi korinish -->
<script type="text/javascript"> 
  var user = '{{ request.user }}'

  function getToken(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i].trim();
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    } 
  }
  return cookieValue;
}
var csrftoken = getToken('csrftoken');
</script>
<!-- tugash qismi -->

</head>

<body>

  <div class="hero_area">
    <div class="bg-box">
      <img src="{% static 'images/aaa.jpg' %}" alt="">
    </div>
    <!-- header section strats -->
    <header class="header_section">
      <div style="margin-top: -15px;" class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'index' %}">
            <span>
              Asaman
            </span>
          </a>
          <style type="text/css">
               button{
                      margin-top:  15px;
                      border: none;
                      text-transform: uppercase;
                      display: inline-block;
                      padding: 10px 55px;
                      background-color: #ffbe33;
                      color: #ffffff;
                      border-radius: 45px;
                      -webkit- transition: all 0.3s;
                      transition: all 0.3s;
                      border: none;
               }
             </style>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  mx-auto ">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'menu' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'book' %}">Book Table</a>
              </li>
            </ul>

            <div class="user_option">
              {% if user.is_authenticated %}
              <div class="dropdown">
              <button class="btn-box" style="margin-top: 50px; ">{{ user.username|title }}</button>
              <div class="dropdown-content">
                <a href="#">Link1</a>
                <a href="#">Link2</a>
                <a href="{% url 'logout' %}">Logout</a>
              </div>
                  <div style="margin-left: 100px!important;   ">
                      <a  href="{% url 'cart' %}"><img id= "cart-icon" src="{% static 'images/carts.png' %}">
                      </a>
                      <p id="cart-total">{{ cartItems }}</p>
                  </div>
<style type="text/css">
  #cart-icon{
  width:49px;
  display: inline-block;
  margin-left: 20px;
  color: red;
  
}
#cart-total{
  display: inline-table;
  text-align: center;
  color:#fff;
  background-color: red;
  margin-top: 20px;
  width: 20px;
  height: 25px;
  border-radius: 50%;
  font-size: 14px;

}
</style>
              {% else %}
              <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="order_online" style="margin: 15px;">Saytga kirish</a>
                <a href="{% url 'signup' %}" class="order_online" style="margin: 15px;">Ro'yhatdan o'tish</a>
              </form>
              
          </div>
          {% endif %}
        </div>
      </nav>
    </div>
  </header>

{% block content %}


{% endblock content %}

<footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +998973892827
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  krmvazimjon16@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              Asaman
            </a>
            <p>
              Asaman, Inc. was founded in 1995 as a specialty pharmaceutical distributor. Initially focused primarily on anti-retroviral therapy solutions, as the demand for new pharmaceutical therapies grew, so did Asaman.
            </p>
            <div class="footer_social">
              <a href="https://m.facebook.com/krmv.azimjon">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="https://www.linkedin.com/in/azimjon-karimov-31666a204/">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="http://instagram.com/kar.1mov7?utm_source=qr">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            Everyday
          </p>
          <p>
            10.00 Am -10.00 Pm
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> By Karimov 
        </p>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <script src="{% static 'js/cart.js' %}"></script>
  <!-- End Google Map -->

</body>

</html>

templates/book.html
{% extends 'base.html' %}

{% block content %}
    <!-- end header section -->
  </div>

  <!-- book section -->
  <section class="book_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2>
          Book A Table
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <form method = "post"> {% csrf_token %}
              <div>
                <input type="text" class="form-control" name = "name" placeholder="Ismingizni kiriting" />
              </div>
              <div>
                <input type="text" class="form-control" name = "phone" placeholder=" Telefon raqamingizni kiriting " />
              </div>
              <div>
                <input type="email" class="form-control" name= "email" placeholder="Emailingizni kiriting" />
              </div>
              <div>
                <input type="text" class="form-control" name= "message" placeholder="Bizga xabaringiz" />
              </div>
              <div class="btn_box">
                <button>
                  Yuborish
                </button>
              </div>
            </form>
          </div>
        </div>
        <div class="col-md-6">
          <div class="map_container ">
            <div id="googleMap"></div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end book section -->

  <!-- footer section -->
{% endblock content %}

templates/cart.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <script src="{% static 'js/cart.js' %}"></script>
    <title>Shopping Cart UI</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart1.css' %}">
    <link rel="stylesheet" type="text/css" href="./style.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,900" rel="stylesheet">

<script type="text/javascript"> 
  var user = '{{ request.user }}'

  function getToken(name) {
  var cookieValue = null;
  if (document.cookie && document.cookie !== '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
      var cookie = cookies[i].trim();
      if (cookie.substring(0, name.length + 1) === (name + '=')) {
        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        break;
      }
    }
  }
  return cookieValue;
}
var csrftoken = getToken('csrftoken');
</script>


</head>
<body>
   <div class="CartContainer">
       <div class="Header">
        <h3 class="Heading">Shopping Cart </h3>
        <h5 class="Action">Remove all</h5>
       </div>
       {% for item in items %}
       <div class="Cart-Items">
          <div class="image-box">
            <img src="{{ item.product.product_image.url }}" width="225px" height="200px" />
          </div>
          <div class="about">
            <h1 class="">{{ item.product.product_name }}</h1>
            <h3 class="subtitle"></h3>
            <img src=""/>
          </div>
          <div class="counter">
            <div class="btn" ><img data-product="{{ item.product.id }}" width="20px" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrowup1.png' %}"></div>
            <div class="count">{{ item.quantity }}</div>
            <div class="btn"><img data-product="{{ item.product.id }}" width="20px" data-action="remove"  class="chg-quantity update-cart" src="{% static  'images/arrow down.png' %}"></div>
          </div>
          <div class="prices">
            <div class="amount">${{ item.product.product_price }}</div>
            <div class="save"><u>Save for later</u></div>
            <div class="remove" data-product="{{ item.product.id }}" data-action="delete"><u>Remove</u></div>
          </div>
       </div>
       <br>
       {% endfor %}
     <hr> 
     <div class="checkout">
     <div class="total">
        <div>
            <div class="Subtotal">Sub-Total</div>
            <div class="items">{{ order.get_card_items }}</div>
        </div>
        <div class="total-amount">${{ order.get_card_total }}</div>
     </div>
     <button class="button">Checkout</button></div>
   </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

templates/example.html
 <div class="col-sm-6 col-lg-4 all pizza">
            {% for page in mahsulotlar %}           
            <div class="box">
              <div>
                <div class="img-box">
                  {% if page.product_image %}
                  <img src="{{ page.product_image.url }}" alt="">
                  {% endif %}
                </div>
                <div class="detail-box">
                  <h5>
                    {{ page.product_name }}
                  </h5>
                  <p id="soz">
                    {{ page.product_compound }}
                  </p>
                  <div class="options">
                    <h6>
                      ${{ page.product_price }}
                    </h6>
                    <a href="">
                      <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 456.029 456.029" style="enable-background:new 0 0 456.029 456.029;" xml:space="preserve">
                        <g>
                          <g>
                            <path d="M345.6,338.862c-29.184,0-53.248,23.552-53.248,53.248c0,29.184,23.552,53.248,53.248,53.248
                         c29.184,0,53.248-23.552,53.248-53.248C398.336,362.926,374.784,338.862,345.6,338.862z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M439.296,84.91c-1.024,0-2.56-0.512-4.096-0.512H112.64l-5.12-34.304C104.448,27.566,84.992,10.67,61.952,10.67H20.48
                         C9.216,10.67,0,19.886,0,31.15c0,11.264,9.216,20.48,20.48,20.48h41.472c2.56,0,4.608,2.048,5.12,4.608l31.744,216.064
                         c4.096,27.136,27.648,47.616,55.296,47.616h212.992c26.624,0,49.664-18.944,55.296-45.056l33.28-166.4
                         C457.728,97.71,450.56,86.958,439.296,84.91z" />
                          </g>
                        </g>
                        <g>
                          <g>
                            <path d="M215.04,389.55c-1.024-28.16-24.576-50.688-52.736-50.688c-29.696,1.536-52.224,26.112-51.2,55.296
                         c1.024,28.16,24.064,50.688,52.224,50.688h1.024C193.536,443.31,216.576,418.734,215.04,389.55z" />
                          </g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                        <g>
                        </g>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %} 
          </div>   -->

templates/product_create.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Feane </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

<div class="hero_area">
    <div class="bg-box">
      <img src="{% static 'images/hero-bg.jpg' %}" alt="">
    </div>
    <!-- header section strats -->
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'index' %}">
            <span>
              Feane
            </span>
          </a>
          </div>
  <!-- book section -->
  <section class="book_section layout_padding">
    <div class="container">
      <div class="heading_container">
        <h2 style="color: white;">
          Yangi mahsulot qoshish
        </h2>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form_container">
            <form method = "post" enctype = "multipart/form-data"> {% csrf_token %}
              <div>
                <input type="text" class="form-control" name = "product_name" id="id_product_name" placeholder="Mahsulot nomi"/>
              </div>
              <div>
                <input type="text" class="form-control" name = "product_compound" id="id_product_compound" placeholder="Mahsulot tarkibi"/>
              </div>
              <div>
              	<h2 style="color: white; font-size: 25px;">Mahsulot rasmi</h2>
              	<style type="">input[type = 'file'] {color: transparent;}</style>
                <input type="file" name= "product_image" accept = "image/*" required= "" id="id_product_image"/>
              </div>
              <br>
              <div>
                <input type="text" name= "product_price" id="id_product_price" placeholder="Mahsulot narxi" />
              </div>
              <div class="btn_box">
                <button type= "submit">
                  Yuborish
                </button>
              </div>
            </form>
          </div>
        </div>
          </div>
        </div>
      </div>
    </div>
  </section>
            </div>
          </div>
        </nav>
      </div>
    </header>

<footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              Feane
            </a>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-pinterest" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            Everyday
          </p>
          <p>
            10.00 Am -10.00 Pm
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a><br><br>
          &copy; <span id="displayYear"></span> Distributed By
          <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
        </p>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->

</body>

</html>


<!-- <form method = "post" enctype = "multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button type = "submit">yuborish</button>
</form>